use rdev::{Button, Event, EventType, Key};
use serde::{Deserialize, Serialize};
use std::time::SystemTime;

// Serializable version of rdev::Event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SerializableEvent {
    pub time: SystemTime,
    pub event_type: SerializableEventType,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SerializableEventType {
    KeyPress(SerializableKey),
    KeyRelease(SerializableKey),
    ButtonPress(SerializableButton),
    ButtonRelease(SerializableButton),
    MouseMove { x: f64, y: f64 },
    Wheel { delta_x: i64, delta_y: i64 },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SerializableKey {
    Alt,
    AltGr,
    Backspace,
    CapsLock,
    ControlLeft,
    ControlRight,
    Delete,
    DownArrow,
    End,
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Home,
    LeftArrow,
    MetaLeft,
    MetaRight,
    PageDown,
    PageUp,
    Return,
    RightArrow,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    UpArrow,
    PrintScreen,
    ScrollLock,
    Pause,
    NumLock,
    BackQuote,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Num0,
    Minus,
    Equal,
    KeyQ,
    KeyW,
    KeyE,
    KeyR,
    KeyT,
    KeyY,
    KeyU,
    KeyI,
    KeyO,
    KeyP,
    LeftBracket,
    RightBracket,
    KeyA,
    KeyS,
    KeyD,
    KeyF,
    KeyG,
    KeyH,
    KeyJ,
    KeyK,
    KeyL,
    SemiColon,
    Quote,
    BackSlash,
    IntlBackslash,
    KeyZ,
    KeyX,
    KeyC,
    KeyV,
    KeyB,
    KeyN,
    KeyM,
    Comma,
    Dot,
    Slash,
    Insert,
    KpReturn,
    KpMinus,
    KpPlus,
    KpMultiply,
    KpDivide,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    Function,
    Unknown(u32),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SerializableButton {
    Left,
    Right,
    Middle,
    Unknown(u8),
}

// Convert from rdev types to serializable types
impl From<Event> for SerializableEvent {
    fn from(event: Event) -> Self {
        SerializableEvent {
            time: event.time,
            event_type: event.event_type.into(),
        }
    }
}

impl From<EventType> for SerializableEventType {
    fn from(event_type: EventType) -> Self {
        match event_type {
            EventType::KeyPress(key) => SerializableEventType::KeyPress(key.into()),
            EventType::KeyRelease(key) => SerializableEventType::KeyRelease(key.into()),
            EventType::ButtonPress(button) => SerializableEventType::ButtonPress(button.into()),
            EventType::ButtonRelease(button) => SerializableEventType::ButtonRelease(button.into()),
            EventType::MouseMove { x, y } => SerializableEventType::MouseMove { x, y },
            EventType::Wheel { delta_x, delta_y } => {
                SerializableEventType::Wheel { delta_x, delta_y }
            }
        }
    }
}

impl From<Key> for SerializableKey {
    fn from(key: Key) -> Self {
        match key {
            Key::Alt => SerializableKey::Alt,
            Key::AltGr => SerializableKey::AltGr,
            Key::Backspace => SerializableKey::Backspace,
            Key::CapsLock => SerializableKey::CapsLock,
            Key::ControlLeft => SerializableKey::ControlLeft,
            Key::ControlRight => SerializableKey::ControlRight,
            Key::Delete => SerializableKey::Delete,
            Key::DownArrow => SerializableKey::DownArrow,
            Key::End => SerializableKey::End,
            Key::Escape => SerializableKey::Escape,
            Key::F1 => SerializableKey::F1,
            Key::F2 => SerializableKey::F2,
            Key::F3 => SerializableKey::F3,
            Key::F4 => SerializableKey::F4,
            Key::F5 => SerializableKey::F5,
            Key::F6 => SerializableKey::F6,
            Key::F7 => SerializableKey::F7,
            Key::F8 => SerializableKey::F8,
            Key::F9 => SerializableKey::F9,
            Key::F10 => SerializableKey::F10,
            Key::F11 => SerializableKey::F11,
            Key::F12 => SerializableKey::F12,
            Key::Home => SerializableKey::Home,
            Key::LeftArrow => SerializableKey::LeftArrow,
            Key::MetaLeft => SerializableKey::MetaLeft,
            Key::MetaRight => SerializableKey::MetaRight,
            Key::PageDown => SerializableKey::PageDown,
            Key::PageUp => SerializableKey::PageUp,
            Key::Return => SerializableKey::Return,
            Key::RightArrow => SerializableKey::RightArrow,
            Key::ShiftLeft => SerializableKey::ShiftLeft,
            Key::ShiftRight => SerializableKey::ShiftRight,
            Key::Space => SerializableKey::Space,
            Key::Tab => SerializableKey::Tab,
            Key::UpArrow => SerializableKey::UpArrow,
            Key::PrintScreen => SerializableKey::PrintScreen,
            Key::ScrollLock => SerializableKey::ScrollLock,
            Key::Pause => SerializableKey::Pause,
            Key::NumLock => SerializableKey::NumLock,
            Key::BackQuote => SerializableKey::BackQuote,
            Key::Num1 => SerializableKey::Num1,
            Key::Num2 => SerializableKey::Num2,
            Key::Num3 => SerializableKey::Num3,
            Key::Num4 => SerializableKey::Num4,
            Key::Num5 => SerializableKey::Num5,
            Key::Num6 => SerializableKey::Num6,
            Key::Num7 => SerializableKey::Num7,
            Key::Num8 => SerializableKey::Num8,
            Key::Num9 => SerializableKey::Num9,
            Key::Num0 => SerializableKey::Num0,
            Key::Minus => SerializableKey::Minus,
            Key::Equal => SerializableKey::Equal,
            Key::KeyQ => SerializableKey::KeyQ,
            Key::KeyW => SerializableKey::KeyW,
            Key::KeyE => SerializableKey::KeyE,
            Key::KeyR => SerializableKey::KeyR,
            Key::KeyT => SerializableKey::KeyT,
            Key::KeyY => SerializableKey::KeyY,
            Key::KeyU => SerializableKey::KeyU,
            Key::KeyI => SerializableKey::KeyI,
            Key::KeyO => SerializableKey::KeyO,
            Key::KeyP => SerializableKey::KeyP,
            Key::LeftBracket => SerializableKey::LeftBracket,
            Key::RightBracket => SerializableKey::RightBracket,
            Key::KeyA => SerializableKey::KeyA,
            Key::KeyS => SerializableKey::KeyS,
            Key::KeyD => SerializableKey::KeyD,
            Key::KeyF => SerializableKey::KeyF,
            Key::KeyG => SerializableKey::KeyG,
            Key::KeyH => SerializableKey::KeyH,
            Key::KeyJ => SerializableKey::KeyJ,
            Key::KeyK => SerializableKey::KeyK,
            Key::KeyL => SerializableKey::KeyL,
            Key::SemiColon => SerializableKey::SemiColon,
            Key::Quote => SerializableKey::Quote,
            Key::BackSlash => SerializableKey::BackSlash,
            Key::IntlBackslash => SerializableKey::IntlBackslash,
            Key::KeyZ => SerializableKey::KeyZ,
            Key::KeyX => SerializableKey::KeyX,
            Key::KeyC => SerializableKey::KeyC,
            Key::KeyV => SerializableKey::KeyV,
            Key::KeyB => SerializableKey::KeyB,
            Key::KeyN => SerializableKey::KeyN,
            Key::KeyM => SerializableKey::KeyM,
            Key::Comma => SerializableKey::Comma,
            Key::Dot => SerializableKey::Dot,
            Key::Slash => SerializableKey::Slash,
            Key::Insert => SerializableKey::Insert,
            Key::KpReturn => SerializableKey::KpReturn,
            Key::KpMinus => SerializableKey::KpMinus,
            Key::KpPlus => SerializableKey::KpPlus,
            Key::KpMultiply => SerializableKey::KpMultiply,
            Key::KpDivide => SerializableKey::KpDivide,
            Key::Kp0 => SerializableKey::Kp0,
            Key::Kp1 => SerializableKey::Kp1,
            Key::Kp2 => SerializableKey::Kp2,
            Key::Kp3 => SerializableKey::Kp3,
            Key::Kp4 => SerializableKey::Kp4,
            Key::Kp5 => SerializableKey::Kp5,
            Key::Kp6 => SerializableKey::Kp6,
            Key::Kp7 => SerializableKey::Kp7,
            Key::Kp8 => SerializableKey::Kp8,
            Key::Kp9 => SerializableKey::Kp9,
            Key::Function => SerializableKey::Function,
            Key::Unknown(code) => SerializableKey::Unknown(code),
            _ => SerializableKey::Unknown(0), // Catch-all for any other variants
        }
    }
}

impl From<Button> for SerializableButton {
    fn from(button: Button) -> Self {
        match button {
            Button::Left => SerializableButton::Left,
            Button::Right => SerializableButton::Right,
            Button::Middle => SerializableButton::Middle,
            Button::Unknown(code) => SerializableButton::Unknown(code),
        }
    }
}

// Convert from serializable types back to rdev types
impl From<SerializableEvent> for Event {
    fn from(event: SerializableEvent) -> Self {
        Event {
            time: event.time,
            event_type: event.event_type.into(),
            unicode: None,
            platform_code: 0,
            position_code: 0,
            extra_data: 0,
            usb_hid: 0,
        }
    }
}

impl From<SerializableEventType> for EventType {
    fn from(event_type: SerializableEventType) -> Self {
        match event_type {
            SerializableEventType::KeyPress(key) => EventType::KeyPress(key.into()),
            SerializableEventType::KeyRelease(key) => EventType::KeyRelease(key.into()),
            SerializableEventType::ButtonPress(button) => EventType::ButtonPress(button.into()),
            SerializableEventType::ButtonRelease(button) => EventType::ButtonRelease(button.into()),
            SerializableEventType::MouseMove { x, y } => EventType::MouseMove { x, y },
            SerializableEventType::Wheel { delta_x, delta_y } => {
                EventType::Wheel { delta_x, delta_y }
            }
        }
    }
}

impl From<SerializableKey> for Key {
    fn from(key: SerializableKey) -> Self {
        match key {
            SerializableKey::Alt => Key::Alt,
            SerializableKey::AltGr => Key::AltGr,
            SerializableKey::Backspace => Key::Backspace,
            SerializableKey::CapsLock => Key::CapsLock,
            SerializableKey::ControlLeft => Key::ControlLeft,
            SerializableKey::ControlRight => Key::ControlRight,
            SerializableKey::Delete => Key::Delete,
            SerializableKey::DownArrow => Key::DownArrow,
            SerializableKey::End => Key::End,
            SerializableKey::Escape => Key::Escape,
            SerializableKey::F1 => Key::F1,
            SerializableKey::F2 => Key::F2,
            SerializableKey::F3 => Key::F3,
            SerializableKey::F4 => Key::F4,
            SerializableKey::F5 => Key::F5,
            SerializableKey::F6 => Key::F6,
            SerializableKey::F7 => Key::F7,
            SerializableKey::F8 => Key::F8,
            SerializableKey::F9 => Key::F9,
            SerializableKey::F10 => Key::F10,
            SerializableKey::F11 => Key::F11,
            SerializableKey::F12 => Key::F12,
            SerializableKey::Home => Key::Home,
            SerializableKey::LeftArrow => Key::LeftArrow,
            SerializableKey::MetaLeft => Key::MetaLeft,
            SerializableKey::MetaRight => Key::MetaRight,
            SerializableKey::PageDown => Key::PageDown,
            SerializableKey::PageUp => Key::PageUp,
            SerializableKey::Return => Key::Return,
            SerializableKey::RightArrow => Key::RightArrow,
            SerializableKey::ShiftLeft => Key::ShiftLeft,
            SerializableKey::ShiftRight => Key::ShiftRight,
            SerializableKey::Space => Key::Space,
            SerializableKey::Tab => Key::Tab,
            SerializableKey::UpArrow => Key::UpArrow,
            SerializableKey::PrintScreen => Key::PrintScreen,
            SerializableKey::ScrollLock => Key::ScrollLock,
            SerializableKey::Pause => Key::Pause,
            SerializableKey::NumLock => Key::NumLock,
            SerializableKey::BackQuote => Key::BackQuote,
            SerializableKey::Num1 => Key::Num1,
            SerializableKey::Num2 => Key::Num2,
            SerializableKey::Num3 => Key::Num3,
            SerializableKey::Num4 => Key::Num4,
            SerializableKey::Num5 => Key::Num5,
            SerializableKey::Num6 => Key::Num6,
            SerializableKey::Num7 => Key::Num7,
            SerializableKey::Num8 => Key::Num8,
            SerializableKey::Num9 => Key::Num9,
            SerializableKey::Num0 => Key::Num0,
            SerializableKey::Minus => Key::Minus,
            SerializableKey::Equal => Key::Equal,
            SerializableKey::KeyQ => Key::KeyQ,
            SerializableKey::KeyW => Key::KeyW,
            SerializableKey::KeyE => Key::KeyE,
            SerializableKey::KeyR => Key::KeyR,
            SerializableKey::KeyT => Key::KeyT,
            SerializableKey::KeyY => Key::KeyY,
            SerializableKey::KeyU => Key::KeyU,
            SerializableKey::KeyI => Key::KeyI,
            SerializableKey::KeyO => Key::KeyO,
            SerializableKey::KeyP => Key::KeyP,
            SerializableKey::LeftBracket => Key::LeftBracket,
            SerializableKey::RightBracket => Key::RightBracket,
            SerializableKey::KeyA => Key::KeyA,
            SerializableKey::KeyS => Key::KeyS,
            SerializableKey::KeyD => Key::KeyD,
            SerializableKey::KeyF => Key::KeyF,
            SerializableKey::KeyG => Key::KeyG,
            SerializableKey::KeyH => Key::KeyH,
            SerializableKey::KeyJ => Key::KeyJ,
            SerializableKey::KeyK => Key::KeyK,
            SerializableKey::KeyL => Key::KeyL,
            SerializableKey::SemiColon => Key::SemiColon,
            SerializableKey::Quote => Key::Quote,
            SerializableKey::BackSlash => Key::BackSlash,
            SerializableKey::IntlBackslash => Key::IntlBackslash,
            SerializableKey::KeyZ => Key::KeyZ,
            SerializableKey::KeyX => Key::KeyX,
            SerializableKey::KeyC => Key::KeyC,
            SerializableKey::KeyV => Key::KeyV,
            SerializableKey::KeyB => Key::KeyB,
            SerializableKey::KeyN => Key::KeyN,
            SerializableKey::KeyM => Key::KeyM,
            SerializableKey::Comma => Key::Comma,
            SerializableKey::Dot => Key::Dot,
            SerializableKey::Slash => Key::Slash,
            SerializableKey::Insert => Key::Insert,
            SerializableKey::KpReturn => Key::KpReturn,
            SerializableKey::KpMinus => Key::KpMinus,
            SerializableKey::KpPlus => Key::KpPlus,
            SerializableKey::KpMultiply => Key::KpMultiply,
            SerializableKey::KpDivide => Key::KpDivide,
            SerializableKey::Kp0 => Key::Kp0,
            SerializableKey::Kp1 => Key::Kp1,
            SerializableKey::Kp2 => Key::Kp2,
            SerializableKey::Kp3 => Key::Kp3,
            SerializableKey::Kp4 => Key::Kp4,
            SerializableKey::Kp5 => Key::Kp5,
            SerializableKey::Kp6 => Key::Kp6,
            SerializableKey::Kp7 => Key::Kp7,
            SerializableKey::Kp8 => Key::Kp8,
            SerializableKey::Kp9 => Key::Kp9,
            SerializableKey::Function => Key::Function,
            SerializableKey::Unknown(code) => Key::Unknown(code),
        }
    }
}

impl From<SerializableButton> for Button {
    fn from(button: SerializableButton) -> Self {
        match button {
            SerializableButton::Left => Button::Left,
            SerializableButton::Right => Button::Right,
            SerializableButton::Middle => Button::Middle,
            SerializableButton::Unknown(code) => Button::Unknown(code),
        }
    }
}
